### PR TITLE
Update exception_mailer.rb

### PR DESCRIPTION
**Pull request by kacperjurak**
Hi. I think the layout path in Mailer is wrong. It gives Missing template mailers/layouts/mailer error.

### CODE REVIEW

**Comment by kacperjurak** [comment]
Thank you. Could you create new gem version with change? Can't use git repo because it is few hundred megabytes.

**Comment by richpeck** [comment]
Sorry yes I've been looking at getting the repo fixed, I stupidly included all my PSD files which added up to 100mb's. I'll do it now

**Comment by richpeck** [comment]
Okay so I removed all the offending files with BFS but it's still a 500mb file. I've emailed Github and am exploring further methods to fix it. I'll also get some time in the next few weeks to fix some of the issues in the repo, like the readme etc.

**Comment by richpeck** [comment]
I also pushed the new version of the gem (thanks for the contribution)

**Comment by richpeck** [comment]
Okay I managed to get it down to 100mb but that's obviously still a lot. I'll come back and see if more can be done. The tags/releases were the culprit

**Pull request merged**
