### PR TITLE
ExceptionController inherit ApplicationController

### PR DESCRIPTION
**Pull request by vince94320**

### CODE REVIEW

**Comment by Hallx** [comment]
:+1:

**Comment by richpeck** [comment]
Thanks for this, but I'm going to leave it as it stands *for now*. The reason I didn't inherit from `ApplicationController` was because of the `layout` I usually set in the app controller. I'll have to think of a way around this, as obviously a lot of people like to inherit from their main controller.

**Comment by richpeck** [comment]
This is now changed in the new version (0.4)

**Comment by vince94320** [comment]
great !

**Pull request closed without merging**
